DROP TABLE HomeLoanPage3.Page3;

DROP SCHEMA HomeLoanPage3 RESTRICT;

CREATE SCHEMA HomeLoanPage3;

CREATE TABLE HomeLoanPage3.Page3(
    ID INTEGER NOT NULL PRIMARY KEY
    GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    c_ID INTEGER NOT NULL,
    email varchar(255),
    phone INTEGER,
    postcode INTEGER
);