DROP TABLE HomeLoanPage4.Page4;

DROP SCHEMA HomeLoanPage4 RESTRICT;

CREATE SCHEMA HomeLoanPage4;

CREATE TABLE HomeLoanPage4.Page4(
    ID INTEGER NOT NULL PRIMARY KEY
    GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    c_ID INTEGER NOT NULL,
    loan double
);